### ISSUE TITLE
Error in the framework.cmake file.

### ISSUE THREAD

**Issue by maxou783** [steevo87/thermalvis#103]
In the current framework.cmake file there is an error line 49. 
The "_include(cmake/configure_catkin.cmake)_" needs to be changed in "_include(cmake/configure/catkin.cmake)_".
With the current version ROS users cannot build the package as the _catkin_make_ command produces an error due to this line.

**Comment by steevo87** [comment]
Sorry about that - I just recently moved some files and this was an oversight. I've just pushed the fix that you suggested.

Thanks for your feedback.
