### ISSUE TITLE
Building issues with OpenCV 3.0.0 and other dependencies 

### ISSUE THREAD

**Issue by srinathos** [steevo87/thermalvis#107]
Hi, 
I've been trying to build this library with the required dependencies but have been facing a few issues. I know that the project is not being actively developed, but I was hoping to get some clarity on the build process that I am following. 

Using the instructions from the wiki, I'm using the following to build the library 
- OpenCV 3.0.0
- Boost 1.61
- MSVC 16 2019

Errors:
- I get the error ```Provided path for OpenCV does not appear to contain valid debug OR release
  libraries!``` for the pre-built 3.0.0 and 3.2.0 binaries. Even with a source build 4.2.0 I get the same issue. 
- After adjusting the directory structure in the cmake/find/opencv.cmake. I get the following -- ```Could NOT find OpenCV (missing: opencv_contrib opencv_legacy opencv_viz)``` and OpenCV_FOUND is set to False.

Questions:
- The wiki installation page says to use OpenCV 3.0.0 pre-built, but in order to use the contrib and viz (VTK) module, OpenCV needs to be built from source. 
- opencv_legacy appears to have been deprecated and was not detected in the OpenCV 3.0.0 binaries. 
Could you shed some light on this? I feel I might be missing something here. 

Cheers

**Comment by srinathos** [comment]
Could not figure out the exact issue. One might encounter an issue building old versions of OpenCV with MSVC 16 2019. 

However, building this library is easier/straightforward with the right version of Boost and OpenCV in Linux.

**Comment by Ri-Bai** [comment]
> Hi, I've been trying to build this library with the required dependencies but have been facing a few issues. I know that the project is not being actively developed, but I was hoping to get some clarity on the build process that I am following.
> 
> Using the instructions from the wiki, I'm using the following to build the library
> 
> * OpenCV 3.0.0
> * Boost 1.61
> * MSVC 16 2019
> 
> Errors:
> 
> * I get the error `Provided path for OpenCV does not appear to contain valid debug OR release libraries!` for the pre-built 3.0.0 and 3.2.0 binaries. Even with a source build 4.2.0 I get the same issue.
> * After adjusting the directory structure in the cmake/find/opencv.cmake. I get the following -- `Could NOT find OpenCV (missing: opencv_contrib opencv_legacy opencv_viz)` and OpenCV_FOUND is set to False.
> 
> Questions:
> 
> * The wiki installation page says to use OpenCV 3.0.0 pre-built, but in order to use the contrib and viz (VTK) module, OpenCV needs to be built from source.
> * opencv_legacy appears to have been deprecated and was not detected in the OpenCV 3.0.0 binaries.
>   Could you shed some light on this? I feel I might be missing something here.
> 
> Cheers

Hello， I want to ask you how you  solve this problem"Provided path for OpenCV does not appear to contain valid debug OR release libraries!",I can not understand what you do to get success. please give my a more clear  way. Thank you,I use Ubuntu 18.04 and failed.

**Comment by srinathos** [comment]
@Baser-Bai I had those errors while trying to build for windows. It's been a while, but, if I recall correctly, building for Ubuntu worked fine for me. What version of OpenCV are you using?

**Comment by Ri-Bai** [comment]
> @Baser-Bai I had those errors while trying to build for windows. It's been a while, but, if I recall correctly, building for Ubuntu worked fine for me. What version of OpenCV are you using?

Thank you. I follow your way install opencv  but failed .my cmake  version is 3.10.2
And . I install the OpenCV 3.1.0  success and but cannot use in the thermalvis .the bugs like some version problem.
which  version of cmake are you using? and can you give me your files of opencv3.0.0 that your have success built and installed ? my  email: 3129669048.qq.com. Hope for your reply. Thanks again.

**Comment by Ri-Bai** [comment]
> @Baser-Bai I had those errors while trying to build for windows. It's been a while, but, if I recall correctly, building for Ubuntu worked fine for me. What version of OpenCV are you using?

Thanks  for your reply and  I get your email just now. I do some work ,and success catkin_make this project .But I now confuse about how to use this code .what I need to do first is to  visualize a infrare-camera which is connected by LAN Port.  So, Any advice or help would be great. I want to start it but no idea
